name: Docs Builder

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11


    - name: Install packages
      run: sudo apt-get install python3-sphinx; pip install pipenv; pipenv install --dev

    - name: Build docs
      run: pipenv run sphinx-build -Wab html ./docs ./sosw-rtd

    - name: Configure AWS secrets
      run: aws configure set aws_access_key_id ${{secrets.AWS_ACCESS_KEY_ID}}; aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY}}; aws configure set default.region us-west-2

    - name: Synchronise sample docs
      run: VERSION=`cat setup.py | grep version | awk -F\' '{print $2}'`; cd sosw-rtd; aws s3 sync . s3://sosw-documentation-${{secrets.ACCOUNT_ID}}/junkyard/${{github.ref.name}} --acl public-read

